# fly.toml app configuration file generated for spark-api on 2024-07-11T15:54:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spark-api'
primary_region = 'atl'

[build]
  [args]
    NODE_VERSION = "18"
[http_service]
  internal_port = 7000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']


[[vm]]
  size = 'shared-cpu-1x'
